### ISSUE TITLE
npm run debug throws an error

### ISSUE THREAD

**Issue by scrumastervijaynew** [EdenwareApps/Megacubo#64]
i pulled the main branch and trying to run in the windows vs code environment.

npm run debug throws below error
serve clear
[main] Initializing node...
ELECTRON: object
[main] Loading modules...
[main] Modules loaded.
[main] Initializing window...
[main] Initializing window...
[main] Initializing window... 3
[main] Main initialized.
[main] Initializing window... 4
Bridge server started undefined
Unhandled rejection at: Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'search')
      at Lists.relevantKeywords (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1862354)
      at ListsLoader.prepareUpdater (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1806718)
      at processes.some.processes.push.promise.queue.add.priority (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1808804)      
      at async E:\\Megacubo\www\nodejs\dist\main.cjs:1:1798463
} reason: TypeError: Cannot read properties of undefined (reading 'search')
    at Lists.relevantKeywords (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1862354)
    at ListsLoader.prepareUpdater (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1806718)
    at processes.some.processes.push.promise.queue.add.priority (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1808804)        
    at async E:\\Megacubo\www\nodejs\dist\main.cjs:1:1798463 TypeError: Cannot read properties of undefined (reading 'search')
    at Lists.relevantKeywords (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1862354)
    at ListsLoader.prepareUpdater (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1806718)
    at processes.some.processes.push.promise.queue.add.priority (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1808804)        
    at async E:\\Megacubo\www\nodejs\dist\main.cjs:1:1798463
[main] Initializing window... 5
TypeError: Cannot read properties of undefined (reading 'enable')
    at App.<anonymous> (E:\\Megacubo\www\nodejs\dist\main.cjs:1:2540079)
    at Object.onceWrapper (node:events:633:26)
    at App.emit (node:events:518:28)
    at App.emit (node:domain:488:12)
    at n._init (node:electron/js2c/browser_init:2:12345)
    at initAppWindow (E:\\Megacubo\www\nodejs\dist\main.cjs:1:2541355)
::::::::::: DRIVER LOADED jimp-worker.js -
serve clear
TypeError: Cannot read properties of undefined (reading 'search')
    at Lists.relevantKeywords (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1862354)
    at List.verifyListRelevance (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1769308)
    at List.setIndex (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1768090)
    at ListIndex.<anonymous> (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1767651)
    at ListIndex.emit (node:events:518:28)
    at ListIndex.emit (node:domain:488:12)
    at E:\\Megacubo\www\nodejs\dist\main.cjs:1:1764670
uncaughtException: {
   "code": "ERR_UNHANDLED_ERROR",
   "context": "Unhandled Rejection at: [object Promise], reason: TypeError: Cannot read properties of undefined (reading 'search') | \"TypeError: Cannot read properties of undefined (reading 'search')\\n    at Lists.relevantKeywords (E:\\\\Megacubo\\\\www\\\\nodejs\\\\dist\\\\updater-worker.js:1:1868021)\\n    at ListsLoader.prepareUpdater (E:\\\\Megacubo\\\\www\\\\nodejs\\\\dist\\\\updater-worker.js:1:1815589)\\n    at E:\\\\Megacubo\\\\www\\\\nodejs\\\\dist\\\\updater-worker.js:1:1817675\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async E:\\\\Megacubo\\\\www\\\\nodejs\\\\dist\\\\updater-worker.js:1:1807334\"",
   "stack": "Error [ERR_UNHANDLED_ERROR]: Unhandled error. (`Unhandled Rejection at: [object Promise], reason: TypeError: Cannot read properties of undefined (reading 'search') | \"TypeError: Cannot read properties of undefined (reading 'search')\\\\n    at Lists.relevantKeywords (E:\\\\\\\\\Megacubo\\\\\\\\www\\\\\\\\nodejs\\\\\\\\dist\\\\\\\\updater-worker.js:1:1868021)\\\\n    at ListsLoader.prepareUpdater (E:\\\\\\\\\Megacubo\\\\\\\\www\\\\\\\\nodejs\\\\\\\\dist\\\\\\\\updater-worker.js:1:1815589)\\\\n    at E:\\\\\\\\\Megacubo\\\\\\\\www\\\\\\\\nodejs\\\\\\\\dist\\\\\\\\updater-worker.js:1:1817675\\\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\\\n    at async E:\\\\\\\\\Megacubo\\\\\\\\www\\\\\\\\nodejs\\\\\\\\dist\\\\\\\\updater-worker.js:1:1807334\"`)\n    at Proxy.emit (node:events:507:17)\n    at Proxy.emit (node:domain:488:12)\n    at Worker.<anonymous> (E:\\\Megacubo\\www\\nodejs\\dist\\main.cjs:1:1790178)\n    at Worker.emit (node:events:518:28)\n    at Worker.emit (node:domain:488:12)\n    at MessagePort.<anonymous> (node:internal/worker:262:53)\n    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20)\n    at exports.emitMessage (node:internal/per_context/messageport:23:28)"
} Error [ERR_UNHANDLED_ERROR]: Unhandled error. (`Unhandled Rejection at: [object Promise], reason: TypeError: Cannot read properties of undefined (reading 'search') | "TypeError: Cannot read properties of undefined (reading 'search')\\n    at Lists.relevantKeywords (E:\\\\Megacubo\\\\www\\\\nodejs\\\\dist\\\\updater-worker.js:1:1868021)\\n    at ListsLoader.prepareUpdater (E:\\\\Megacubo\\\\www\\\\nodejs\\\\dist\\\\updater-worker.js:1:1815589)\\n    at E:\\\\Megacubo\\\\www\\\\nodejs\\\\dist\\\\updater-worker.js:1:1817675\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async E:\\\\Megacubo\\\\www\\\\nodejs\\\\dist\\\\updater-worker.js:1:1807334"`)
    at Proxy.emit (node:events:507:17)
    at Proxy.emit (node:domain:488:12)
    at Worker.<anonymous> (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1790178)
    at Worker.emit (node:events:518:28)
    at Worker.emit (node:domain:488:12)
    at MessagePort.<anonymous> (node:internal/worker:262:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (`Unhandled Rejection at: [object Promise], reason: TypeError: Cannot read properties of undefined (reading 'search') | "TypeError: Cannot read properties of undefined (reading 'search')\\n    at Lists.relevantKeywords (E:\\\\Megacubo\\\\www\\\\nodejs\\\\dist\\\\updater-worker.js:1:1868021)\\n    at ListsLoader.prepareUpdater (E:\\\\Megacubo\\\\www\\\\nodejs\\\\dist\\\\updater-worker.js:1:1815589)\\n    at E:\\\\Megacubo\\\\www\\\\nodejs\\\\dist\\\\updater-worker.js:1:1817675\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async E:\\\\Megacubo\\\\www\\\\nodejs\\\\dist\\\\updater-worker.js:1:1807334"`)
    at Proxy.emit (node:events:507:17)
    at Proxy.emit (node:domain:488:12)
    at Worker.<anonymous> (E:\\Megacubo\www\nodejs\dist\main.cjs:1:1790178)
    at Worker.emit (node:events:518:28)
    at Worker.emit (node:domain:488:12)
    at MessagePort.<anonymous> (node:internal/worker:262:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
APP_EXIT
::::::::::: DRIVER LOADED updater-worker.js -
Unhandled Rejection at: [object Promise], reason: TypeError: Cannot read properties of undefined (reading 'search') | "TypeError: Cannot read properties of undefined (reading 'search')\n    at Lists.relevantKeywords (E:\\\Megacubo\\www\\nodejs\\dist\\updater-worker.js:1:1868021)\n    at ListsLoader.prepareUpdater (E:\\\Megacubo\\www\\nodejs\\dist\\updater-worker.js:1:1815589)\n    at E:\\\Megacubo\\www\\nodejs\\dist\\updater-worker.js:1:1817675\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async E:\\\Megacubo\\www\\nodejs\\dist\\updater-worker.js:1:1807334" Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'search')
      at Lists.relevantKeywords (E:\\Megacubo\www\nodejs\dist\updater-worker.js:1:1868021)
      at ListsLoader.prepareUpdater (E:\\Megacubo\www\nodejs\dist\updater-worker.js:1:1815589)
      at E:\\Megacubo\www\nodejs\dist\updater-worker.js:1:1817675
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async E:\\Megacubo\www\nodejs\dist\updater-worker.js:1:1807334
} reason: TypeError: Cannot read properties of undefined (reading 'search')
    at Lists.relevantKeywords (E:\\Megacubo\www\nodejs\dist\updater-worker.js:1:1868021)
    at ListsLoader.prepareUpdater (E:\\Megacubo\www\nodejs\dist\updater-worker.js:1:1815589)
    at E:\\Megacubo\www\nodejs\dist\updater-worker.js:1:1817675
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\\Megacubo\www\nodejs\dist\updater-worker.js:1:1807334
Bridge server started undefined

**Comment by EdenwareApps** [comment]
Fixed with the latest commit. Please [try again](https://github.com/EdenwareApps/Megacubo/blob/master/DEVELOPING.md) and let us know if any problems occur.

**Comment by scrumastervijaynew** [comment]
yes it works now.
