### ISSUE TITLE
udp url playback

### ISSUE THREAD

**Issue by scrumastervijaynew** [EdenwareApps/Megacubo#68]
i am trying to play the udp playback url, but always throws an error "Stream type unknown". Is there any patch available for this issue?

**Comment by scrumastervijaynew** [comment]
i have added the uds.js adapter as same as rtmp.js but unable to play the udp url. please let me if there any patch available?

**Comment by EdenwareApps** [comment]
Hi @scrumastervijaynew, [this is the necessary change](https://github.com/EdenwareApps/Megacubo/commit/1fee61fefd5e3f1f643837ea6fe0cca2f5674676). You also need to run 'rollup -c' in the root folder of the project after any changes to regenerate the files in the 'www/nodejs/dist' folder.

This change will be implemented by default starting with version 17.5.1, which will be released in the next few days.

**Comment by scrumastervijaynew** [comment]
hi @EdenwareApps 
thanks for the patch. I added the relevant code as per the latest commit. And i stream the mp4 file into udp://@127.0.0.1:10000
and try play using Tool-> open url and m3u playlist with that udp url. but i am getting the Offline broadcast : unreachable.however the same url i am able to play vlc player. the logs as below:
STREAMER INTENT {
  name: '@127.0.0.1',
  url: 'udp://@127.0.0.1:10000',
  terms: { name: [ '@127', '0.0.1' ], group: [] }
} undefined
STREAMER INTENT {
  name: '@127.0.0.1',
  url: 'udp://@127.0.0.1:10000',
  terms: { name: [ '@127', '0.0.1' ], group: [] }
}
osd-show Connecting @127.0.0.1...
udp://@127.0.0.1:10000
DownloadStream:http udp://@127.0.0.1:10000 TypeError: Cannot read property 'match' of null
    at DownloadStreamHttp.encodeURI (E:\Megacubo\www\nodejs\dist\main.js:1:1505508)
    at DownloadStreamHttp.options (E:\Megacubo\www\nodejs\dist\main.js:1:1501835)
    at DownloadStreamHttp.start (E:\Megacubo\www\nodejs\dist\main.js:1:1503442)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
TypeError: Cannot read property 'match' of null
    at DownloadStreamHttp.encodeURI (E:\Megacubo\www\nodejs\dist\main.js:1:1505508)
    at DownloadStreamHttp.options (E:\Megacubo\www\nodejs\dist\main.js:1:1501835)
    at DownloadStreamHttp.start (E:\Megacubo\www\nodejs\dist\main.js:1:1503442)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[15780:0723/122530.045:INFO:CONSOLE(1)] "theming undefined undefined undefined undefined undefined", source: http://127.0.0.1:60983/renderer/dist/renderer.js (1)
[15780:0723/122530.046:INFO:CONSOLE(1)] "theming pre renderbackground [object Object]", source: http://127.0.0.1:60983/renderer/dist/renderer.js (1)
[15780:0723/122530.048:INFO:CONSOLE(1)] "theming renderbackground [object Object]", source: http://127.0.0.1:60983/renderer/dist/renderer.js (1)
[15780:0723/122530.049:INFO:CONSOLE(1)] "DATA [object Object]", source: http://127.0.0.1:60983/renderer/dist/renderer.js (1)
[15780:0723/122530.054:INFO:CONSOLE(1)] "animateBackground slow-desktop", source: http://127.0.0.1:60983/renderer/dist/renderer.js (1)
[15780:0723/122530.071:INFO:CONSOLE(1)] "set-loading [object Object] true", source: http://127.0.0.1:60983/renderer/dist/renderer.js (1)
[15780:0723/122530.071:INFO:CONSOLE(1)] "set-loading [object Object] true", source: http://127.0.0.1:60983/renderer/dist/renderer.js (1)    
DownloadStream:http udp://@127.0.0.1:10000 TypeError: Cannot read property 'match' of null
    at DownloadStreamHttp.encodeURI (E:\Megacubo\www\nodejs\dist\main.js:1:1505508)
    at DownloadStreamHttp.options (E:\Megacubo\www\nodejs\dist\main.js:1:1501835)
    at DownloadStreamHttp.start (E:\Megacubo\www\nodejs\dist\main.js:1:1503442)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
TypeError: Cannot read property 'match' of null
    at DownloadStreamHttp.encodeURI (E:\Megacubo\www\nodejs\dist\main.js:1:1505508)
    at DownloadStreamHttp.options (E:\Megacubo\www\nodejs\dist\main.js:1:1501835)
    at DownloadStreamHttp.start (E:\Megacubo\www\nodejs\dist\main.js:1:1503442)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
DownloadStream:http udp://@127.0.0.1:10000 TypeError: Cannot read property 'match' of null
    at DownloadStreamHttp.encodeURI (E:\Megacubo\www\nodejs\dist\main.js:1:1505508)
    at DownloadStreamHttp.options (E:\Megacubo\www\nodejs\dist\main.js:1:1501835)
    at DownloadStreamHttp.start (E:\Megacubo\www\nodejs\dist\main.js:1:1503442)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
TypeError: Cannot read property 'match' of null
    at DownloadStreamHttp.encodeURI (E:\Megacubo\www\nodejs\dist\main.js:1:1505508)
    at DownloadStreamHttp.options (E:\Megacubo\www\nodejs\dist\main.js:1:1501835)
    at DownloadStreamHttp.start (E:\Megacubo\www\nodejs\dist\main.js:1:1503442)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
STREAMER INTENT ERROR -1
STREAMSTATE SAVE 1721717730.794
streamer stop()
handleFailure -1 stop {
  name: '@127.0.0.1',
  url: 'udp://@127.0.0.1:10000',
  terms: { name: [ '@127', '0.0.1' ], group: [] }
}
osd-show Offline broadcast: Unreachable

**Comment by scrumastervijaynew** [comment]
i want just play the udp url in the player without encoding or transcoding. is there any option/flag to set?
